git checkout -b tempBranch
npm i
echo ...
echo ...
echo ...
echo ...
echo run the scripts
echo ...
echo ...
echo ...
echo ...
echo deleteing the dat ato make sure they are readded by the scripts
rm -f data/countries/* data/us/*
echo should be deleted now
ls -al data/countries
ls -al data/us
echo did it work?
echo ...
echo ...
echo ...
echo ...
node scripts/fetchDataForAllStates.js
node scripts/fetchWorldData.js
echo ...
echo ...
echo ...
echo ...
ls -al data
ls -al data/us
ls -al data/countries
echo ...
echo ...
echo ...
echo ...
echo done running the script
echo ...
echo ...
echo ...
echo ...
echo git add .
git add .
echo git commit -m 'daily update'
git commit -m 'daily update'
echo git push -u origin tempBranch
git push -u origin tempBranch
echo done